//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        public Rooms()
        {
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int Room_ID { get; set; }
        public int Number { get; set; }
        public Nullable<int> ToR_ID { get; set; }
    
        public virtual ICollection<Reservation> Reservation { get; set; }
        public virtual ToR ToR { get; set; }
    }
}
