//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToR
    {
        public ToR()
        {
            this.Rooms = new HashSet<Rooms>();
            this.ToR_Services = new HashSet<ToR_Services>();
        }
    
        public int ToR_ID { get; set; }
        public string Title { get; set; }
        public int Price { get; set; }
        public int Area { get; set; }
        public int CoP { get; set; }
    
        public virtual ICollection<Rooms> Rooms { get; set; }
        public virtual ICollection<ToR_Services> ToR_Services { get; set; }
    }
}
