//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToR_Services
    {
        public int ToRS_ID { get; set; }
        public int ToR_ID { get; set; }
        public int Service_ID { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual ToR ToR { get; set; }
    }
}
