//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Guestbook = new HashSet<Guestbook>();
            this.News = new HashSet<News>();
            this.Reservation = new HashSet<Reservation>();
            this.User_Info = new HashSet<User_Info>();
        }
    
        public int User_ID { get; set; }
        public string Email { get; set; }
        public bool isAdmin { get; set; }
        public Nullable<System.DateTime> LastEnter { get; set; }
        public int EnterCount { get; set; }
    
        public virtual ICollection<Guestbook> Guestbook { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<Reservation> Reservation { get; set; }
        public virtual ICollection<User_Info> User_Info { get; set; }
    }
}
